openapi: 3.0.0
info:
  title: Calculate Tool API
  version: 1.0.0
  description: Evaluates a basic arithmetic expression and returns the result or an error.

paths:
  /calculate:
    post:
      summary: Evaluate an arithmetic expression
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - expression
              properties:
                expression:
                  type: string
                  example: "2 + 3 * 4"
      responses:
        '200':
          description: Successful evaluation
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - required: ["result"]
                    properties:
                      result:
                        type: number
                        example: 14
                  - required: ["error"]
                    properties:
                      error:
                        type: string
                        example: "division by zero"

